{{- if .Values.autoscalingHttp.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
  namespace: "{{ .Chart.Name }}-{{ .Values.environment }}"
  labels:
    app: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
    environment: {{ .Values.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
  minReplicas: {{ .Values.autoscalingHttp.minReplicas }}
  maxReplicas: {{ .Values.autoscalingHttp.maxReplicas }}
  metrics:
    {{- if .Values.autoscalingHttp.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscalingHttp.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscalingHttp.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscalingHttp.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
