apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret-{{ .Values.environment }}"
  namespace: "{{ .Chart.Name }}-{{ .Values.environment }}"
  labels:
    app: "{{ .Chart.Name }}-secret-{{ .Values.environment }}"
    environment: {{ .Values.environment }}
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
