apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
  namespace: "{{ .Chart.Name }}-{{ .Values.environment }}"
  labels:
    app: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
    environment: {{ .Values.environment }}
spec:
  selector:
    app: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
  type: ClusterIP
  ports:
    - name: "{{ .Chart.Name }}-http-{{ .Values.environment }}"
      port: 80
      targetPort: 3000
      protocol: TCP
